[
  {
    "Time":"07:00",
    "CNA \/ RN Note":"RN admit: Weak, dry mucous membranes, coarse L > R bases.",
    "HR":82,
    "HRV (ms)":60,
    "RR":18,
    "SpO2 (%)":96,
    "PI":5.0,
    "MAP":84,
    "Temp (\u00b0C)":37.1,
    "PQD Risk":0.1,
    "PQD State":"Baseline",
    "Std Monitor State":"Stable"
  },
  {
    "Time":"08:00",
    "CNA \/ RN Note":"CNA: Two warm blankets given; ate 25% breakfast; repositioned right.",
    "HR":86,
    "HRV (ms)":49,
    "RR":19,
    "SpO2 (%)":96,
    "PI":4.7,
    "MAP":82,
    "Temp (\u00b0C)":37.2,
    "PQD Risk":0.45,
    "PQD State":"Yellow",
    "Std Monitor State":"No data"
  },
  {
    "Time":"09:00",
    "CNA \/ RN Note":"CNA: Patient sleeping.",
    "HR":88,
    "HRV (ms)":43,
    "RR":19,
    "SpO2 (%)":96,
    "PI":4.4,
    "MAP":80,
    "Temp (\u00b0C)":37.3,
    "PQD Risk":0.5,
    "PQD State":"Yellow (sustained)",
    "Std Monitor State":"No data"
  },
  {
    "Time":"10:00",
    "CNA \/ RN Note":"CNA: Removed linens per patient request.",
    "HR":92,
    "HRV (ms)":37,
    "RR":20,
    "SpO2 (%)":96,
    "PI":4.1,
    "MAP":79,
    "Temp (\u00b0C)":37.5,
    "PQD Risk":0.62,
    "PQD State":"Orange",
    "Std Monitor State":"No data"
  },
  {
    "Time":"12:00",
    "CNA \/ RN Note":"RN: Drowsy but oriented \u00d74; lungs coarse L > R; O\u2082 95 % RA.",
    "HR":94,
    "HRV (ms)":33,
    "RR":21,
    "SpO2 (%)":95,
    "PI":3.8,
    "MAP":77,
    "Temp (\u00b0C)":37.7,
    "PQD Risk":0.78,
    "PQD State":"Red",
    "Std Monitor State":"Stable"
  },
  {
    "Time":"13:00",
    "CNA \/ RN Note":"System auto-notify.",
    "HR":96,
    "HRV (ms)":28,
    "RR":22,
    "SpO2 (%)":95,
    "PI":3.5,
    "MAP":77,
    "Temp (\u00b0C)":37.9,
    "PQD Risk":0.82,
    "PQD State":"Red (sustained)",
    "Std Monitor State":"No data"
  },
  {
    "Time":"15:00",
    "CNA \/ RN Note":"CNA: Refused lunch.",
    "HR":100,
    "HRV (ms)":24,
    "RR":23,
    "SpO2 (%)":94,
    "PI":3.2,
    "MAP":76,
    "Temp (\u00b0C)":38.1,
    "PQD Risk":0.88,
    "PQD State":"Red",
    "Std Monitor State":"No data"
  },
  {
    "Time":"16:00",
    "CNA \/ RN Note":"RN: Drowsy alert and oriented \u00d74; O\u2082 94 % 2 L NC.",
    "HR":104,
    "HRV (ms)":22,
    "RR":24,
    "SpO2 (%)":94,
    "PI":3.0,
    "MAP":75,
    "Temp (\u00b0C)":38.3,
    "PQD Risk":0.9,
    "PQD State":"Red",
    "Std Monitor State":"Watch"
  },
  {
    "Time":"18:00",
    "CNA \/ RN Note":"System log: Critical risk persisting.",
    "HR":108,
    "HRV (ms)":20,
    "RR":25,
    "SpO2 (%)":93,
    "PI":2.9,
    "MAP":70,
    "Temp (\u00b0C)":38.4,
    "PQD Risk":0.93,
    "PQD State":"Red",
    "Std Monitor State":"Alarm"
  }
]
